# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75f9ea7b879288a72f149ae45e5e5f7110684f5c4e53699a12b0ab988dce7f6762d916d7705e88f5ef6e37a77b7df8f741e82ed7b858d66fc5d81b113d56963b

test:
  secret_key_base: 65fa11fbb47c0559011a574024b39eddd2ad424bd6488ada6f7fd15c24fc6659439b2c037da6bd4c4ac544c81fd9b1907f08c21d9fc3f215911060d319213eb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
